language: java

jdk:
  - oraclejdk8
  
sudo: required

before_install:
  # Install Atlassian SDK
  - sudo sh -c 'echo "deb https://packages.atlassian.com/atlassian-sdk-deb stable contrib" >>/etc/apt/sources.list'
  - sudo curl -O https://packages.atlassian.com/api/gpg/key/public
  - sudo apt-key add public
  - sudo apt-get update
  - sudo apt-get install atlassian-plugin-sdk

install:
  - atlas-mvn -q org.apache.maven.plugins:maven-dependency-plugin:resolve-plugins --batch-mode

script:
  - atlas-mvn -q clean install --batch-mode -Dbitbucket.test.version=$BITBUCKET_TEST_VERSION

env:
  matrix:
    - BITBUCKET_TEST_VERSION=4.6.4
    - BITBUCKET_TEST_VERSION=4.10.2
    - BITBUCKET_TEST_VERSION=5.7.1

cache:
# Caching is not allowed for 'sudo: required' builds.
# It is kept for future usage.
  directories:
    - $HOME/.m2
